id: IE408E806
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:20:18+00:00'
last_modified: '2022-06-10T05:32:10.684516+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18844
  title: གཞུང་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CC0E:
      image_group_id: I8LS18846
      title: Volume 1 of gzhung lam skor gyi krung hwa mi dmangs spyi mthun rgyal
        khab kyi bca' khrims/
      total_pages: 60
      order: 1
      base_file: CC0E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
